FIX: hough transform

diff --git a/Lab1/makefile b/Lab1/makefile
--- a/Lab1/makefile
+++ b/Lab1/makefile
@@ -6,6 +6,7 @@ CCFLAGS=-Wall -lm
 SRC=src
 INCL=incl
 EXECUTABLE_NAME=hough
+COMPILED=false
 
 
 #### COLORS ####
@@ -28,20 +29,37 @@ PUR_COLOR := \033[0;35m
 
 SOURCES := $(wildcard $(SRC)/*.c)
 OBJECTS := $(patsubst $(SRC)/%.c, $(SRC)/%.o, $(SOURCES))
-.SILENT: all $(EXECUTABLE_NAME) $(SRC)/%.o clean $(CC) make $(SOURCES) $(OBJECTS)
+.SILENT: all $(EXECUTABLE_NAME) $(SRC)/%.o clean $(CC) make $(SOURCES) $(OBJECTS) hough.o
+.PHONY: $(EXECUTABLE_NAME)
 
-all: clean $(EXECUTABLE_NAME)
-	@echo "$(PUR_COLOR)Ejecutable generado!$(NO_COLOR) Nombre: $(OK_COLOR)$(EXECUTABLE_NAME)$(NO_COLOR) "
+all: $(EXECUTABLE_NAME)
+	@if [ $(COMPILED) = true ]; then \
+		echo "$(PUR_COLOR)Ejecutable generado!$(NO_COLOR) Nombre: $(OK_COLOR)$(EXECUTABLE_NAME)$(NO_COLOR) ";\
+	fi
 
-$(EXECUTABLE_NAME): $(OBJECTS)
-	@echo "Generando ejecutable ..."
-	$(CC) -o $@ $^ hough.c  $(CCFLAGS)  
+$(EXECUTABLE_NAME): $(OBJECTS) hough.o
+	@if [ $(COMPILED) = false ]; then \
+		echo "$(OK_COLOR)**************************************************$(NO_COLOR)";\
+		echo "$(OK_COLOR)*$(NO_COLOR)  No existen cambios, no se volverá a compilar  $(OK_COLOR)*$(NO_COLOR)";\
+		echo "$(OK_COLOR)**************************************************$(NO_COLOR)";\
+	else\
+		echo "Generando ejecutable ...";\
+		$(CC) -o $@ $^ $(CCFLAGS) ;\
+	fi
+
+hough.o: hough.c
+	@echo "Generando archivos object de $@ ...."
+	($(CC)  -I$(SRC) -c hough.c  -o $@ $(CCFLAGS) && echo "$(OK_COLOR)[OK]$(NO_COLOR)") \
+		||  (echo "$(ERROR_COLOR)[ERROR]$(NO_COLOR)" && exit 1; )
+	$(eval COMPILED=true)
+	
 
 $(SRC)/%.o: $(SRC)/%.c $(INCL)/%.h
 	@echo "Generando archivos object de $@ ...."
 	($(CC)  -I$(SRC) -c $< -o $@ $(CCFLAGS) && echo "$(OK_COLOR)[OK]$(NO_COLOR)") \
 		||  (echo "$(ERROR_COLOR)[ERROR]$(NO_COLOR)" && exit 1; )
+	$(eval COMPILED=true)
 clean:
 	@echo "Eliminado $(WARN_COLOR).o $(NO_COLOR)y $(WARN_COLOR)$(EXECUTABLE_NAME) $(NO_COLOR) antiguos..."
-	rm -f $(SRC)/*.o $(EXECUTABLE_NAME)
+	rm -f $(SRC)/*.o $(EXECUTABLE_NAME) *.o
 
